version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: mongo_dbJs
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: nest_app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/financial_db
    volumes:
      - .:/app
    command: npm run start:prod

volumes:
  mongo_data:
